fixes actions and flow

diff --git a/.github/actions/pacttest-uploader/action.yml b/.github/actions/pacttest-uploader/action.yml
--- a/.github/actions/pacttest-uploader/action.yml
+++ b/.github/actions/pacttest-uploader/action.yml
@@ -1,1 +1,37 @@
-test
+name: 'Pacttest uploader'
+description: 'This is a pacttest uploader'
+inputs:
+    DOCKER_IMAGE_URL:
+        description: 'Full URL for docker image'
+        required: true
+runs:
+    using: 'composite'
+    steps:
+    - name: Setup docker container
+      run: |
+        docker container ls -a --no-trunc
+        container_id=`docker create $DOCKER_IMAGE_URL`
+        if [$?=0]; then
+            mkdir -p files
+            docker cp $container_id:/app/pacts files
+            docker rm $container_id -f
+            ls -alhR files
+        else
+            echo 'Unable to run the image - $DOCKER_IMAGE_URL'
+            exit 1
+        fi
+
+        PYTHON_SCRIPT=$(cat <<EOF
+        import glob, os, json, urllib.request
+        version = ${{ github.run_id }}
+        os.chdir('files')
+        for f in glob.glob('*.json'):
+            with open(f) as json_data:
+                pact = json.load(json_data)
+                pact_url = 'http://pact-broker.stg.commercial.csnglobal.net/pacts/provider/{}/consumer/{}/version/{}'.format(pact['provider']['name'],pact['consumer']['name'], 1)
+                print(pact)
+        EOF
+        )
+
+        python -c $PYTHON_SCRIPT
+      shell: bash
